---

- name: Installing fish formulas
  homebrew:
    name: "{{ fish_formulas}}"
    state: present
  when: fish_formulas | list

- name: Creating fish configuration directory
  file:
    path: "{{ ansible_env.HOME }}/.config/fish"
    recurse: yes
    state: directory
  when: fish_config_source_path | string

- name: Updating fish configurations folder
  copy:
    src: "{{ fish_config_source_path }}"
    dest: "{{ ansible_env.HOME }}/.config"
  when: fish_config_source_path | string

- name: Creating fisherman install directory
  file:
    dest: "{{ ansible_env.HOME }}/.config/fish/functions"
    recurse: yes
    state: directory
  when: fish_formulas | list

- name: Installing fisherman
  get_url:
    url: https://git.io/fisher
    dest: "{{ ansible_env.HOME }}/.config/fish/functions/fisher.fish"
  when: fish_formulas | list

- name: Retrieving installed fisherman packages
  shell: fisher list
  args:
    executable: /usr/local/bin/fish
  register: fisherman_plugins
  changed_when: false
  failed_when: false
  tags:   # This needs fish
    - skip_ansible_lint
  when: fish_formulas | list

- name: Installing fish plugins
  shell: fisher install {{ item }}
  args:
    executable: /usr/local/bin/fish
  with_items: "{{ fish_plugins }}"
  when: "fish_formulas | list and item not in fisherman_plugins.stdout"
  tags:   # This needs fish
    - skip_ansible_lint

- name: Updating theme configuration
  copy:
    src: "{{ starship_source_path }}"
    dest: "{{ ansible_env.HOME }}/.config/starship.toml"
  when: mysql_config_source_file | string
