---

- name: Installing mas formulas
  homebrew:
    name: "{{ mas_formulas }}"
    state: present

- name: Listing installed MAS apps
  command: mas list
  register: mas_list
  check_mode: no
  changed_when: false

- name: Ensuring MAS apps are installed
  command: mas install "{{ item.id }}"
  with_items: "{{ mas_applications }}"
  when: (item.id | string) not in mas_list.stdout
