---

- name: Installing mas formulas
  homebrew:
    name: "{{ mas_formulas }}"
    state: latest
    update_homebrew: yes

- name: Listing installed MAS apps
  command: mas list
  register: mas_list
  check_mode: no
  changed_when: false

- name: Ensuring MAS apps are installed
  command: mas install "{{ item.id }}"
  with_items: "{{ mas_applications }}"
  when: (item.id | string) not in mas_list.stdout

- name: Upgrading MAS apps
  command: mas upgrade
  register: mas_upgrade_status
  changed_when: "'Everything is up-to-date' not in mas_upgrade_status.stdout"
