---

- name: Installing tmux formulas
  homebrew:
    name: "{{ tmux_formulas }}"
    state: present

- name: Installing Tmux Plugin Manager
  git:
    repo: https://github.com/tmux-plugins/tpm
    depth: "1"
    force: yes
    recursive: yes
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
